#!/bin/bash
base="AppIcon.png"
target=$(find . -iname 'AppIcon.appiconset')
convert "$base" -resize '16x16'     "$target/AppIcon-16.png"
convert "$base" -resize '32x32'     "$target/AppIcon-16@2x.png"
convert "$base" -resize '32x32'     "$target/AppIcon-32.png"
convert "$base" -resize '64x64'     "$target/AppIcon-32@2x.png"
convert "$base" -resize '128x128'   "$target/AppIcon-128.png"
convert "$base" -resize '256x256'   "$target/AppIcon-128@2x.png"
convert "$base" -resize '256x256'   "$target/AppIcon-256.png"
convert "$base" -resize '512x512'   "$target/AppIcon-256@2x.png"
convert "$base" -resize '512x512'   "$target/AppIcon-512.png"
convert "$base" -resize '1024x1024' "$target/AppIcon-512@2x.png"
